### ISSUE TITLE
has this been tested on ARM?

### ISSUE THREAD

**Issue by openluopworld** [pth5804/SIMON_SPECK_ARM_NEON#1]
Hi, has this been tested on ARM? thanks

**Comment by pth5804** [comment]
Hi, I tested SIMON & SPECK ARM NEON version on RaspberryPi3(ARM Cortex-A53).
If you have any questions, please write a comment.

**Comment by openluopworld** [comment]
That's ok. I am learning the code. Thanks for reply.
